### ISSUE TITLE
I need the icon theme that showed in your screenshot

### ISSUE THREAD

**Issue by Skinyi** [Zortax/Vimix-Midnight#1]
At first, thanks for your excellent work and I really like it, and I think the icon theme in your screenshot really suit the shell theme. But I don`t know what`s the name of the icon theme and how can I get it. I need your help and I will be grateful.

**Comment by zortax** [comment]
Thank you! The Icon theme is called "Flat-Remix" and can be found on [its GitHub page](https://github.com/daniruiz/flat-remix)!
