### ISSUE TITLE
Not worked on gtk2

### ISSUE THREAD

**Issue by Mackel123** [Zortax/Vimix-Midnight#2]
I like the theme very much. But it is not supported on gtk2

**Comment by zortax** [comment]
@Mackel123 Thanks! Sadly, there isn't a simple way to backport a GTK3 theme to GTK2 (as far as I know). As GTK2 themes use a completely different description language, I'd essentially need to recreate the whole theme. Currently I don't have to time to do that. Feel free to open a pull request if you find a way...
